#!/usr/bin/env node
// Generate the DoraHacks version of the submission.
//
// DoraHacks does not render mermaid — it shows the fence as a code block, which
// looks broken on the first page a judge reads. This swaps each fence for the
// rendered PNG and rewrites relative paths to absolute raw.githubusercontent
// URLs, because a relative repo path does not resolve outside GitHub either.
//   npm run diagrams && npm run dorahacks
import { readFileSync, writeFileSync } from 'node:fs';

const BASE = process.env.RAW_BASE
  ?? 'https://raw.githubusercontent.com/okwareddevnest/DreamArena/main/';

const IMG = [
  ['flowchart TD', 'brand/diagrams/01-decision.png', 'How MIRA decides — four of six outcomes are refusals'],
  ['sequenceDiagram', 'brand/diagrams/03-scoring.png', 'What each person gets: their own scored record'],
  ['flowchart LR', 'brand/diagrams/02-architecture.png', 'Architecture — two agents, each with its own key'],
];

let out = readFileSync('SUBMISSION.md', 'utf8').replace(/```mermaid\n([\s\S]*?)```/g, (whole, body) => {
  const hit = IMG.find(([kind]) => body.includes(kind));
  if (!hit) return whole;
  const [, path, alt] = hit;
  return `![${alt}](${BASE}${path})\n\n*${alt}.*`;
});

out = out.replaceAll('src="brand/', `src="${BASE}brand/`);
out = out.replace('| Repository | *(add your GitHub URL)* |',
  `| Repository | ${BASE.replace('https://raw.githubusercontent.com/', 'https://github.com/').replace(/\/main\/$/, '')} |`);

const note = [
  '<!-- GENERATED by npm run dorahacks — edit SUBMISSION.md, not this file.',
  '     Diagrams are images because DoraHacks renders a mermaid fence as a code block.',
  '     Push the repo so the raw URLs resolve, or upload brand/diagrams/*.png with the',
  '     editor image button. Delete this comment before pasting. -->',
  '', '',
].join('\n');

writeFileSync('SUBMISSION-DORAHACKS.md', note + out);
const left = (note + out).split('```mermaid').length - 1;
console.log(`\n  SUBMISSION-DORAHACKS.md written · ${left} mermaid fence(s) remaining\n`);
